apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.component_id}}-build
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - ml
    - workshop  
    - python
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://rhods-dashboard-redhat-ods-applications${{values.cluster_id}}/projects
      title: Red Hat OpenShift AI
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://github.com/${{values.githubOrg}}/${{values.repoName}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}